### PR TITLE
Feature/cah 8 voting screen

### PR DESCRIPTION
**Pull request by andrii-puhach**
Feature/cah 8 voting screen

### CODE REVIEW

**Comment by andrii-puhach** [comment]
Added a lot of stuff
Refactor game screens for android
Refactor game navigation
Fix round screen
**Implemented gameviewmodel for basic game flow (not complete yet)**

Added score screen (not completely)

https://user-images.githubusercontent.com/100288631/220408517-26e66b61-a0e4-4161-9300-34687d820bd5.mp4

**Comment by artem-y-eleks** [comment]
Isn't the voting smiley face at the supposed to be closer to the center of the card here?
smiley_face_at_the_bottom

as opposed to the expected result:
expected_smiley_face_position

**Comment by andrii-puhach** [comment]
> Isn't the voting smiley face at the supposed to be closer to the center of the card here? smiley_face_at_the_bottom
> 
> as opposed to the expected result: expected_smiley_face_position

As I described in the above comment , score screen still in progress. 
But as discussed earlier in the morning we'd like to have something for gameviewmodel to work with

**Review by artem-y-eleks — APPROVED** [review]
🔥 LGTM but feel free to wait for 👀 from Android team if necessary

**Pull request merged**
